//! Runtime BGM: the game has no music files. Every note you hear is
//! generated by `crates/chiptune` while you play.
//!
//! The split matters and is worth stating plainly:
//!
//! * The **composer runs on the main thread**, one or two bars ahead of
//!   the playhead. It reads the game state, decides tempo, mode and
//!   arrangement, and emits notes timestamped in *absolute samples*.
//! * The **audio thread only dispatches**. It owns a [`Synth`], pops
//!   notes whose timestamp has arrived, and produces samples. It has no
//!   concept of BPM, bars, chords or danger â€” so tempo never crosses the
//!   thread boundary, and there is nothing to lock.
//!
//! Bevy's [`Decodable`] trait is what lets us hand raw PCM to `bevy_audio`
//! with no extra dependencies. Note that the stream is spawned with
//! [`PlaybackSettings::ONCE`], never `LOOP`: `LOOP` wraps the decoder in
//! rodio's `repeat_infinite`, which buffers every sample ever produced â€”
//! against a generator that never ends, that is an unbounded leak.
//! Repetition is the composer's job, not the mixer's.

use std::sync::Arc;
use std::sync::Mutex;
use std::sync::atomic::{AtomicBool, AtomicU32, AtomicU64, Ordering};
use std::sync::mpsc::{Receiver, Sender, TryRecvError, channel};

use bevy::asset::Asset;
use bevy::audio::{AddAudioSource, ChannelCount, Decodable, SampleRate, Source, Volume};
use bevy::prelude::*;
use bevy::reflect::TypePath;

use bevytris_chiptune::compose::{Composer, Context, Profile};
use bevytris_chiptune::synth::Synth;
use bevytris_chiptune::{NoteEvent, SAMPLE_RATE, SAMPLES_PER_FRAME};

use crate::audio::{Bgm, spawn_bgm_toast};
use crate::config::GameSettings;
use crate::effects::DangerLevel;
use crate::session::{GameSession, HumanControlled};
use crate::state::{AppState, GameMode, PlayState};

/// How far ahead of the playhead the composer keeps the score filled.
/// Two bars at 140 BPM is about 3.4 s â€” orders of magnitude more than any
/// frame hitch, and short enough that the danger level still steers the
/// music promptly.
const LOOKAHEAD_SECS: f32 = 3.5;

/// State shared with the audio thread. Everything here is a plain atomic:
/// no allocation, no mutex, nothing that can block the callback.
#[derive(Default)]
pub struct Shared {
    /// The authoritative musical clock, in samples.
    pos: AtomicU64,
    /// Zone: slide the whole mix underwater.
    muffle: AtomicBool,
    /// Instantaneous synth envelope, published for the visualizer.
    energy: AtomicU32,
    /// Bumped when a new piece starts. Notes queued under an older
    /// generation are dropped on arrival instead of being played out.
    generation: AtomicU32,
}

impl Shared {
    pub fn pos(&self) -> u64 {
        self.pos.load(Ordering::Relaxed)
    }
    pub fn energy(&self) -> f32 {
        f32::from_bits(self.energy.load(Ordering::Relaxed))
    }
}

/// A note plus the piece it belongs to. The composer runs several seconds
/// ahead of the playhead, so when the music changes there is always a
/// backlog of notes from the *previous* piece already in flight â€” without
/// the stamp they would keep playing for the whole lookahead and the
/// switch would seem not to happen at all.
#[derive(Clone, Copy)]
struct Cmd {
    generation: u32,
    ev: NoteEvent,
}

// ---------------------------------------------------------------------------
// The streaming audio source
// ---------------------------------------------------------------------------

/// The asset `bevy_audio` plays. It carries no samples â€” just the channel
/// the composer writes notes into.
#[derive(Asset, TypePath)]
pub struct ChiptuneStream {
    /// `decoder()` takes `&self` and is called exactly once, so the
    /// receiver is handed over through an `Option` that gets emptied.
    rx: Mutex<Option<Receiver<Cmd>>>,
    shared: Arc<Shared>,
}

pub struct ChiptuneDecoder {
    synth: Synth,
    rx: Option<Receiver<Cmd>>,
    /// One command popped from the channel but not yet due. Events arrive
    /// in time order, so a single slot is enough of a peek.
    held: Option<Cmd>,
    shared: Arc<Shared>,
    generation: u32,
    frame_acc: u32,
    /// The right half of the frame we already generated. rodio wants
    /// interleaved samples, so each frame is handed over in two calls.
    pending_right: Option<f32>,
}

impl Iterator for ChiptuneDecoder {
    type Item = f32;

    fn next(&mut self) -> Option<f32> {
        if let Some(r) = self.pending_right.take() {
            return Some(r);
        }
        let now = self.synth.pos();
        // Read the generation every call rather than once per frame: the
        // composer bumps it and starts sending new notes in the same
        // breath, and a stale read here would discard those instead.
        let generation = self.shared.generation.load(Ordering::Relaxed);
        if generation != self.generation {
            self.generation = generation;
            // Cut whatever is sounding; the new piece starts now.
            self.synth.all_notes_off();
        }
        // Drain everything that has come due, plus anything left over from
        // a piece that is no longer playing. Nothing here allocates.
        loop {
            if let Some(cmd) = self.held {
                if cmd.generation != generation {
                    // Backlog from the previous piece â€” bin it and keep
                    // draining rather than waiting for its timestamp.
                    self.held = None;
                } else if cmd.ev.at > now {
                    break;
                } else {
                    self.synth.note_on(&cmd.ev);
                    self.held = None;
                }
            }
            let Some(rx) = &self.rx else { break };
            match rx.try_recv() {
                Ok(cmd) => self.held = Some(cmd),
                Err(TryRecvError::Empty) => break,
                // The game shut down; keep producing silence rather than
                // ending the stream mid-teardown.
                Err(TryRecvError::Disconnected) => {
                    self.rx = None;
                    break;
                }
            }
        }

        self.frame_acc += 1;
        if self.frame_acc >= SAMPLES_PER_FRAME {
            self.frame_acc = 0;
            self.synth.set_muffled(self.shared.muffle.load(Ordering::Relaxed));
            self.shared
                .energy
                .store(self.synth.envelope().to_bits(), Ordering::Relaxed);
        }
        self.shared.pos.store(now, Ordering::Relaxed);
        let (l, r) = self.synth.next_frame();
        self.pending_right = Some(r);
        Some(l)
    }
}

impl Source for ChiptuneDecoder {
    fn current_span_len(&self) -> Option<usize> {
        None
    }
    fn channels(&self) -> ChannelCount {
        ChannelCount::new(2).expect("stereo")
    }
    fn sample_rate(&self) -> SampleRate {
        SampleRate::new(SAMPLE_RATE).expect("nonzero sample rate")
    }
    fn total_duration(&self) -> Option<std::time::Duration> {
        // Never ends. This is what makes PlaybackSettings::LOOP the wrong
        // choice â€” see the module docs.
        None
    }
}

impl Decodable for ChiptuneStream {
    type Decoder = ChiptuneDecoder;

    fn decoder(&self) -> Self::Decoder {
        let rx = self.rx.lock().ok().and_then(|mut slot| slot.take());
        ChiptuneDecoder {
            synth: Synth::new(),
            rx,
            held: None,
            generation: self.shared.generation.load(Ordering::Relaxed),
            shared: self.shared.clone(),
            frame_acc: 0,
            pending_right: None,
        }
    }
}

// ---------------------------------------------------------------------------
// Composer side
// ---------------------------------------------------------------------------

/// The main-thread half: the composer, its channel to the audio thread,
/// and the smoothed gameplay context it reads.
#[derive(Resource)]
pub struct MusicEngine {
    composer: Composer,
    tx: Sender<Cmd>,
    pub shared: Arc<Shared>,
    scratch: Vec<NoteEvent>,
    profile: Profile,
    profile_age: f32,
    intensity: f32,
    transpose: i32,
    generation: u32,
    /// A new piece is waiting to be anchored to the playhead.
    resync: bool,
    /// Set when the label should be re-announced in the corner.
    announce: bool,
    /// Notes handed to the audio thread since the process started —
    /// only the debug readout reads it.
    sent: u64,
}

/// `BEVYTRIS_MUSIC_DEBUG=1` puts a live readout of the music engine on
/// screen and logs every piece change.
///
/// This exists because the engine is otherwise completely opaque: the
/// composer runs a few seconds ahead of what you can hear, the audio
/// thread owns the clock, and a "the music did not change" report could
/// equally mean the profile never switched, the switch happened but the
/// backlog drowned it, or the arrangement is simply on its opening bars
/// with nothing but a bass line. Those need telling apart by looking.
#[derive(Resource, Clone, Copy)]
pub struct MusicDebug(pub bool);

#[derive(Component)]
struct MusicDebugText;

/// A window of the score around the playhead, for the piano-roll scene.
/// The scene and the sequencer therefore share one clock; deriving beats
/// from `Time::elapsed` instead would drift audibly inside a minute.
#[derive(Resource, Default)]
pub struct ScoreFeed {
    pub notes: Vec<RollNote>,
    pub pos: u64,
    pub bpm: f32,
    /// Quarter notes per bar â€” 4 in common time, 3 in a waltz or in 6/8.
    /// The roll draws a heavy line every this many beats.
    pub quarters_per_bar: u32,
    pub tonic: i32,
    /// Pitch classes that belong to the current mode â€” the piano roll
    /// bands its rows by this, so the backdrop visibly changes key.
    pub scale: [bool; 12],
}

#[derive(Clone, Copy)]
pub struct RollNote {
    pub at: u64,
    pub end: u64,
    pub midi: u8,
    pub voice: u8,
    pub vel: u8,
}

impl ScoreFeed {
    /// Seconds from the playhead to `at`; negative means already played.
    pub fn secs_from_now(&self, at: u64) -> f32 {
        (at as f64 - self.pos as f64) as f32 / SAMPLE_RATE as f32
    }
}

pub struct MusicPlugin;

impl Plugin for MusicPlugin {
    fn build(&self, app: &mut App) {
        let (tx, rx) = channel();
        let shared = Arc::new(Shared::default());
        let seed = seed_from_clock();
        // Built here rather than in a Startup system: bevy_state runs the
        // initial state's OnEnter before PreStartup, and that hook already
        // wants to pick a profile.
        app.insert_resource(MusicEngine {
            composer: Composer::new(seed),
            tx,
            shared: shared.clone(),
            scratch: Vec::with_capacity(512),
            profile: Profile::Ambient,
            profile_age: 0.0,
            intensity: 0.0,
            transpose: 0,
            generation: 0,
            resync: false,
            announce: false,
            sent: 0,
        });
        let debug = matches!(
            std::env::var("BEVYTRIS_MUSIC_DEBUG").as_deref(),
            Ok("1") | Ok("true")
        );
        app.insert_resource(MusicDebug(debug));
        app.insert_resource(PendingStream(Some(ChiptuneStream {
            rx: Mutex::new(Some(rx)),
            shared,
        })));
        app.init_resource::<ScoreFeed>()
            .add_audio_source::<ChiptuneStream>()
            .add_systems(Startup, start_stream)
            .add_systems(
                Update,
                (choose_profile, plan_music, announce_track, music_debug).chain(),
            );
    }
}

/// Holds the asset until [`start_stream`] can reach `Assets<T>`.
#[derive(Resource)]
struct PendingStream(Option<ChiptuneStream>);

fn seed_from_clock() -> u64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0x5EED)
}

fn start_stream(
    mut commands: Commands,
    mut pending: ResMut<PendingStream>,
    mut assets: ResMut<Assets<ChiptuneStream>>,
    settings: Res<GameSettings>,
) {
    let Some(stream) = pending.0.take() else {
        return;
    };
    let handle = assets.add(stream);
    commands.spawn((
        // Tuple form: `AudioPlayer::new` exists only for the built-in
        // AudioSource.
        AudioPlayer(handle),
        // The spawn volume has to be right: `apply_bgm_volume` only
        // touches the sink when the duck factor moves or the settings
        // change, so a placeholder here would simply stay.
        PlaybackSettings::ONCE.with_volume(Volume::Linear(settings.bgm_linear())),
        // The existing volume/duck/pause systems key off this marker, so
        // they keep working untouched.
        Bgm,
    ));
}

/// Which musical personality belongs to a given place in the game.
/// `PlayState` only exists inside `Playing`, hence the `Option`.
fn profile_for(app: AppState, play: Option<PlayState>, mode: GameMode) -> Profile {
    match app {
        AppState::Playing | AppState::Restarting => {
            if play == Some(PlayState::Finished) {
                Profile::Victory
            } else if matches!(mode, GameMode::Single | GameMode::Sprint | GameMode::Dig) {
                Profile::SoloCalm
            } else {
                Profile::VsIntense
            }
        }
        _ => Profile::Ambient,
    }
}

/// Pick the musical personality from where the player actually is.
fn choose_profile(
    time: Res<Time>,
    app_state: Res<State<AppState>>,
    play_state: Option<Res<State<PlayState>>>,
    mode: Res<GameMode>,
    mut engine: ResMut<MusicEngine>,
) {
    let profile = profile_for(*app_state.get(), play_state.map(|s| *s.get()), *mode);
    if profile != engine.profile {
        let was = engine.profile;
        engine.profile = profile;
        engine.profile_age = 0.0;
        engine.transpose = 0;
        let i = engine.intensity;
        engine.composer.set_profile(profile, i);
        // Retire the notes already queued for the previous piece. Without
        // this the old music plays on for the whole lookahead (several
        // seconds) and the change reads as not having happened.
        engine.generation = engine.generation.wrapping_add(1);
        let generation = engine.generation;
        engine
            .shared
            .generation
            .store(generation, Ordering::Relaxed);
        engine.resync = true;
        // Only the real music is worth naming; menus change too often.
        engine.announce = matches!(profile, Profile::SoloCalm | Profile::VsIntense);
        let info = engine.composer.info();
        info!(
            "music: {was:?} -> {profile:?} (gen {generation}) | {} · {} kit | {:?} / {:?}",
            info.label(),
            info.kit.name(),
            app_state.get(),
            mode.into_inner(),
        );
    } else {
        engine.profile_age += time.delta_secs();
    }
}

/// Blend the gameplay signals into one 0..1 intensity and keep the score
/// filled ahead of the playhead.
fn plan_music(
    time: Res<Time>,
    danger: Option<Res<DangerLevel>>,
    sessions: Query<&GameSession, With<HumanControlled>>,
    mut engine: ResMut<MusicEngine>,
    mut feed: ResMut<ScoreFeed>,
) {
    let mut raw = danger.map(|d| d.0[0]).unwrap_or(0.0) * 0.62;
    let mut zone = false;
    for s in &sessions {
        // Garbage on the way and a combo running both raise the stakes
        // without the stack being tall yet.
        raw += 0.24 * (s.game.incoming_total() as f32 / 8.0).min(1.0);
        raw += 0.14 * (s.game.combo().max(0) as f32 / 6.0).min(1.0);
        zone |= s.game.zone_active();
    }
    let raw = raw.clamp(0.0, 1.0);
    // Asymmetric follower, same shape as the danger vignette's: rises
    // quickly, falls back slowly enough that one lucky clear does not
    // drop the music out of gear.
    let rate = if raw > engine.intensity { 3.0 } else { 1.2 };
    let dt = time.delta_secs();
    engine.intensity += (raw - engine.intensity) * (rate * dt).min(1.0);

    engine
        .shared
        .muffle
        .store(zone, std::sync::atomic::Ordering::Relaxed);

    let ctx = Context {
        profile: engine.profile,
        intensity: engine.intensity,
        transpose: engine.transpose,
        zone,
        elapsed: engine.profile_age,
    };
    let pos = engine.shared.pos();
    let lookahead = (LOOKAHEAD_SECS * SAMPLE_RATE as f32) as u64;

    if engine.resync {
        engine.resync = false;
        // The old piece was planned several seconds into the future, so
        // the new one has to be dragged back to the playhead or it would
        // not start until that lookahead ran out.
        engine.composer.seek(pos);
        feed.notes.clear();
    }

    let MusicEngine {
        composer,
        scratch,
        tx,
        generation,
        ..
    } = &mut *engine;
    let generation = *generation;
    scratch.clear();
    composer.advance(pos, lookahead, &ctx, scratch);

    // Mirror every planned note to both consumers: the audio thread, and
    // the piano roll. Same notes, same timestamps, one clock.
    let info = composer.info();
    feed.pos = pos;
    feed.bpm = info.bpm;
    feed.quarters_per_bar = info.meter.quarters_per_bar();
    feed.tonic = info.tonic;
    feed.scale = [false; 12];
    for d in 0..7 {
        let pc = (info.tonic + info.mode.pitch(d)).rem_euclid(12) as usize;
        feed.scale[pc] = true;
    }
    // The final chorus lifted the key: say so, since the toast names it.
    let modulated = composer.take_modulated();

    let mut sent = 0u64;
    for ev in scratch.iter() {
        // A closed channel only happens while the app is shutting down.
        let _ = tx.send(Cmd {
            generation,
            ev: *ev,
        });
        sent += 1;
        feed.notes.push(RollNote {
            at: ev.at,
            end: ev.at + ev.frames as u64 * SAMPLES_PER_FRAME as u64,
            midi: ev.midi,
            voice: ev.voice() as u8,
            vel: ev.vel,
        });
    }
    // Keep a few seconds of history for the trailing half of the roll.
    let cutoff = pos.saturating_sub(SAMPLE_RATE as u64 * 4);
    feed.notes.retain(|n| n.end >= cutoff);

    engine.sent += sent;
    if modulated {
        engine.announce = true;
    }
}

/// Live readout of everything the ear cannot check for itself.
fn music_debug(
    mut commands: Commands,
    debug: Res<MusicDebug>,
    engine: Res<MusicEngine>,
    feed: Res<ScoreFeed>,
    mut text: Query<&mut Text, With<MusicDebugText>>,
) {
    if !debug.0 {
        return;
    }
    let info = engine.composer.info();
    let pos = engine.shared.pos();
    // How far ahead of the playhead the score is filled: if this ever
    // sits at zero the composer is starving and the music will stutter.
    let ahead = (info.bar as f32, feed.notes.len());
    let body = format!(
        "{:?} gen{} piece-bar {} | {} · {} kit\n\
         layers: {}\n\
         playhead {:.1}s  intensity {:.2}  age {:.1}s\n\
         notes sent {}  live {}  energy {:.2}",
        engine.profile,
        engine.generation,
        ahead.0,
        info.label(),
        info.kit.name(),
        // The line that would have made the bare-opening bug obvious in a
        // glance instead of by counting notes.
        info.layer_list(),
        pos as f32 / SAMPLE_RATE as f32,
        engine.intensity,
        engine.profile_age,
        engine.sent,
        ahead.1,
        engine.shared.energy(),
    );
    if let Ok(mut t) = text.single_mut() {
        t.0 = body;
        return;
    }
    commands.spawn((
        Node {
            position_type: PositionType::Absolute,
            left: Val::Px(10.0),
            top: Val::Px(10.0),
            ..default()
        },
        Text::new(body),
        TextFont {
            font_size: FontSize::Px(15.0),
            ..default()
        },
        TextColor(Color::srgba(0.7, 1.0, 0.8, 0.9)),
        GlobalZIndex(40),
        Pickable::IGNORE,
        MusicDebugText,
    ));
}

/// Name the generated track in the corner, exactly where the old
/// "now playing" toast used to name the CC0 file.
fn announce_track(mut commands: Commands, mut engine: ResMut<MusicEngine>) {
    if !engine.announce {
        return;
    }
    engine.announce = false;
    let label = engine.composer.info().label();
    spawn_bgm_toast(&mut commands, &label);
}

#[cfg(test)]
mod tests {
    use super::*;
    use bevytris_chiptune::Inst;

    fn stream() -> (ChiptuneStream, Sender<Cmd>) {
        let (tx, rx) = channel();
        (
            ChiptuneStream {
                rx: Mutex::new(Some(rx)),
                shared: Arc::new(Shared::default()),
            },
            tx,
        )
    }

    fn note(at: u64, generation: u32) -> Cmd {
        Cmd {
            generation,
            ev: NoteEvent {
                at,
                inst: Inst::Pluck,
                midi: 69,
                vel: 120,
                frames: 40,
                arp: None,
                glide: 0,
            },
        }
    }

    fn energy(d: &mut ChiptuneDecoder, n: usize) -> f32 {
        (0..n).map(|_| d.next().unwrap().abs()).sum()
    }

    #[test]
    fn the_decoder_runs_the_clock_and_plays_what_it_is_sent() {
        let (s, tx) = stream();
        let shared = s.shared.clone();
        let mut d = s.decoder();

        let quiet = energy(&mut d, 2_000);
        assert!(quiet < 0.05, "an idle stream should be silent, got {quiet}");

        tx.send(note(2_500, 0)).unwrap();
        let loud = energy(&mut d, 12_000);
        assert!(loud > 1.0, "the scheduled note never sounded, got {loud}");

        // The clock only advances inside next(), which is what makes it
        // the one authority the piano roll can trust. It counts stereo
        // frames, so 14 000 calls is 7 000 of them.
        assert!(shared.pos() >= 6_500, "clock stalled at {}", shared.pos());
    }

    #[test]
    fn the_stream_is_interleaved_stereo() {
        let (s, tx) = stream();
        let mut d = s.decoder();
        // A hard-panned voice: the two channels must differ, which they
        // cannot if the interleaving is wrong.
        tx.send(Cmd {
            generation: 0,
            ev: NoteEvent {
                at: 100,
                inst: Inst::Echo,
                midi: 72,
                vel: 127,
                frames: 200,
                arp: None,
                glide: 0,
            },
        })
        .unwrap();
        let mut left = 0.0f32;
        let mut right = 0.0f32;
        for i in 0..24_000 {
            let v = d.next().unwrap().abs();
            if i % 2 == 0 { left += v } else { right += v }
        }
        assert!(left > 0.0 && right > 0.0);
        assert!(
            right > left * 1.3,
            "the counter voice is not panned right ({left} vs {right})"
        );
    }

    #[test]
    fn the_stream_never_ends_even_when_the_composer_goes_away() {
        let (s, tx) = stream();
        assert_eq!(s.decoder().channels().get(), 2);
        assert_eq!(s.decoder().sample_rate().get(), SAMPLE_RATE);
        // total_duration() must stay None: a finite answer would let
        // PlaybackSettings::LOOP wrap us in rodio's buffering repeat.
        assert!(s.decoder().total_duration().is_none());

        let (s2, tx2) = stream();
        let mut d = s2.decoder();
        drop(tx2);
        drop(tx);
        for _ in 0..5_000 {
            assert!(d.next().is_some(), "stream ended after disconnect");
        }
    }

    #[test]
    fn the_decoder_is_only_handed_out_once() {
        let (s, _tx) = stream();
        let first = s.decoder();
        let mut second = s.decoder();
        assert!(first.rx.is_some());
        // A second decoder gets no channel rather than stealing events,
        // and still produces silence instead of panicking.
        assert!(second.rx.is_none());
        assert!(second.next().is_some());
    }

    #[test]
    fn every_screen_maps_to_the_right_music() {
        use AppState::*;
        // Menus are menus whatever mode is selected behind them.
        for mode in [
            GameMode::Single,
            GameMode::Sprint,
            GameMode::Dig,
            GameMode::VsCpu { stage: 15 },
            GameMode::ZoneBattle { stage: 15 },
            GameMode::Custom,
        ] {
            for app in [Title, Settings, SoloSelect, StageSelect, ZoneSelect, CustomSetup] {
                assert_eq!(
                    profile_for(app, None, mode),
                    Profile::Ambient,
                    "{app:?} should stay on menu music"
                );
            }
            // A match is a match from the countdown onwards.
            for play in [
                PlayState::Countdown,
                PlayState::Running,
                PlayState::Paused,
                PlayState::RoundOver,
            ] {
                let want = match mode {
                    GameMode::Single | GameMode::Sprint | GameMode::Dig => Profile::SoloCalm,
                    _ => Profile::VsIntense,
                };
                assert_eq!(profile_for(Playing, Some(play), mode), want, "{mode:?}");
            }
            // The result screen is a fanfare regardless of mode.
            assert_eq!(
                profile_for(Playing, Some(PlayState::Finished), mode),
                Profile::Victory
            );
            // A restart bounces through Restarting with no PlayState at
            // all; the music must not fall back to the menu for that frame.
            assert_ne!(profile_for(Restarting, None, mode), Profile::Ambient);
        }
    }

    /// The title-to-match bug: the composer plans several seconds ahead,
    /// so at the moment the screen changes there is a backlog of the old
    /// piece's notes already queued. They used to play out in full, which
    /// made the switch look like it had not happened.
    #[test]
    fn a_new_piece_retires_the_notes_still_queued_for_the_old_one() {
        let (s, tx) = stream();
        let shared = s.shared.clone();
        let mut d = s.decoder();

        // A lookahead's worth of the old piece: notes spread over the
        // next several seconds.
        for i in 0..200u64 {
            tx.send(note(4_000 + i * 1_200, 0)).unwrap();
        }
        // Let a couple of them sound, then start a new piece.
        let before = energy(&mut d, 12_000);
        assert!(before > 100.0, "the old piece never started, got {before}");
        shared.generation.store(1, Ordering::Relaxed);

        // Nothing from the old backlog may be heard again, even though its
        // timestamps are still ahead of the playhead. (The first block
        // still carries the release ramp of the notes that were sounding
        // at the moment of the cut, so it is skipped.)
        energy(&mut d, 8_000);
        let after = energy(&mut d, 60_000);
        assert!(
            after < 1.0,
            "stale notes kept playing after the cut, got {after} (was {before} per 12k before)"
        );

        // ...and the new piece is audible immediately.
        let now = shared.pos();
        tx.send(note(now + 500, 1)).unwrap();
        assert!(
            energy(&mut d, 12_000) > 1.0,
            "the new piece never started"
        );
    }

    #[test]
    fn a_cut_silences_notes_that_are_already_sounding() {
        let (s, tx) = stream();
        let shared = s.shared.clone();
        let mut d = s.decoder();
        // A long note, mid-ring.
        tx.send(Cmd {
            generation: 0,
            ev: NoteEvent {
                at: 100,
                inst: Inst::Sustain,
                midi: 69,
                vel: 127,
                frames: 600,
                arp: None,
                glide: 0,
            },
        })
        .unwrap();
        assert!(energy(&mut d, 8_000) > 1.0);
        shared.generation.store(7, Ordering::Relaxed);
        // Skip the release ramp and the high-pass settling, then confirm
        // it really stopped. (These counts are interleaved samples, so a
        // stereo frame is two of them.)
        energy(&mut d, 6_000);
        let after = energy(&mut d, 8_000);
        assert!(after < 0.2, "note rang on through the cut, got {after}");
    }
}
