//! Runtime BGM: the game has no music files. Every note you hear is
//! generated by `crates/chiptune` while you play.
//!
//! The split matters and is worth stating plainly:
//!
//! * The **composer runs on the main thread**, one or two bars ahead of
//!   the playhead. It reads the game state, decides tempo, mode and
//!   arrangement, and emits notes timestamped in *absolute samples*.
//! * The **audio thread only dispatches**. It owns a [`Synth`], pops
//!   notes whose timestamp has arrived, and produces samples. It has no
//!   concept of BPM, bars, chords or danger — so tempo never crosses the
//!   thread boundary, and there is nothing to lock.
//!
//! Bevy's [`Decodable`] trait is what lets us hand raw PCM to `bevy_audio`
//! with no extra dependencies. Note that the stream is spawned with
//! [`PlaybackSettings::ONCE`], never `LOOP`: `LOOP` wraps the decoder in
//! rodio's `repeat_infinite`, which buffers every sample ever produced —
//! against a generator that never ends, that is an unbounded leak.
//! Repetition is the composer's job, not the mixer's.

use std::sync::Arc;
use std::sync::Mutex;
use std::sync::atomic::{AtomicBool, AtomicU32, AtomicU64, Ordering};
use std::sync::mpsc::{Receiver, Sender, TryRecvError, channel};

use bevy::asset::Asset;
use bevy::audio::{AddAudioSource, ChannelCount, Decodable, SampleRate, Source, Volume};
use bevy::prelude::*;
use bevy::reflect::TypePath;

use bevytris_chiptune::compose::{Composer, Context, Profile};
use bevytris_chiptune::synth::Synth;
use bevytris_chiptune::{NoteEvent, SAMPLE_RATE, SAMPLES_PER_FRAME};

use crate::audio::{Bgm, spawn_bgm_toast};
use crate::config::GameSettings;
use crate::effects::DangerLevel;
use crate::session::{GameSession, HumanControlled};
use crate::state::{AppState, GameMode, PlayState};

/// How far ahead of the playhead the composer keeps the score filled.
/// Two bars at 140 BPM is about 3.4 s — orders of magnitude more than any
/// frame hitch, and short enough that the danger level still steers the
/// music promptly.
const LOOKAHEAD_SECS: f32 = 3.5;

/// State shared with the audio thread. Everything here is a plain atomic:
/// no allocation, no mutex, nothing that can block the callback.
#[derive(Default)]
pub struct Shared {
    /// The authoritative musical clock, in samples.
    pos: AtomicU64,
    /// Zone: slide the whole mix underwater.
    muffle: AtomicBool,
    /// Instantaneous synth envelope, published for the visualizer.
    energy: AtomicU32,
}

impl Shared {
    pub fn pos(&self) -> u64 {
        self.pos.load(Ordering::Relaxed)
    }
    pub fn energy(&self) -> f32 {
        f32::from_bits(self.energy.load(Ordering::Relaxed))
    }
}

// ---------------------------------------------------------------------------
// The streaming audio source
// ---------------------------------------------------------------------------

/// The asset `bevy_audio` plays. It carries no samples — just the channel
/// the composer writes notes into.
#[derive(Asset, TypePath)]
pub struct ChiptuneStream {
    /// `decoder()` takes `&self` and is called exactly once, so the
    /// receiver is handed over through an `Option` that gets emptied.
    rx: Mutex<Option<Receiver<NoteEvent>>>,
    shared: Arc<Shared>,
}

pub struct ChiptuneDecoder {
    synth: Synth,
    rx: Option<Receiver<NoteEvent>>,
    /// One event popped from the channel but not yet due. Events arrive in
    /// time order, so a single slot is enough of a peek.
    held: Option<NoteEvent>,
    shared: Arc<Shared>,
    frame_acc: u32,
}

impl Iterator for ChiptuneDecoder {
    type Item = f32;

    fn next(&mut self) -> Option<f32> {
        let now = self.synth.pos();
        // Drain everything that has come due. Nothing here allocates.
        loop {
            if let Some(ev) = self.held {
                if ev.at > now {
                    break;
                }
                self.synth.note_on(&ev);
                self.held = None;
            }
            let Some(rx) = &self.rx else { break };
            match rx.try_recv() {
                Ok(ev) => self.held = Some(ev),
                Err(TryRecvError::Empty) => break,
                // The game shut down; keep producing silence rather than
                // ending the stream mid-teardown.
                Err(TryRecvError::Disconnected) => {
                    self.rx = None;
                    break;
                }
            }
        }

        self.frame_acc += 1;
        if self.frame_acc >= SAMPLES_PER_FRAME {
            self.frame_acc = 0;
            self.synth.set_muffled(self.shared.muffle.load(Ordering::Relaxed));
            self.shared
                .energy
                .store(self.synth.envelope().to_bits(), Ordering::Relaxed);
        }
        self.shared.pos.store(now, Ordering::Relaxed);
        Some(self.synth.next_sample())
    }
}

impl Source for ChiptuneDecoder {
    fn current_span_len(&self) -> Option<usize> {
        None
    }
    fn channels(&self) -> ChannelCount {
        ChannelCount::new(1).expect("mono")
    }
    fn sample_rate(&self) -> SampleRate {
        SampleRate::new(SAMPLE_RATE).expect("nonzero sample rate")
    }
    fn total_duration(&self) -> Option<std::time::Duration> {
        // Never ends. This is what makes PlaybackSettings::LOOP the wrong
        // choice — see the module docs.
        None
    }
}

impl Decodable for ChiptuneStream {
    type Decoder = ChiptuneDecoder;

    fn decoder(&self) -> Self::Decoder {
        let rx = self.rx.lock().ok().and_then(|mut slot| slot.take());
        ChiptuneDecoder {
            synth: Synth::new(),
            rx,
            held: None,
            shared: self.shared.clone(),
            frame_acc: 0,
        }
    }
}

// ---------------------------------------------------------------------------
// Composer side
// ---------------------------------------------------------------------------

/// The main-thread half: the composer, its channel to the audio thread,
/// and the smoothed gameplay context it reads.
#[derive(Resource)]
pub struct MusicEngine {
    composer: Composer,
    tx: Sender<NoteEvent>,
    pub shared: Arc<Shared>,
    scratch: Vec<NoteEvent>,
    profile: Profile,
    profile_age: f32,
    intensity: f32,
    transpose: i32,
    /// Set when the label should be re-announced in the corner.
    announce: bool,
}

/// A window of the score around the playhead, for the piano-roll scene.
/// The scene and the sequencer therefore share one clock; deriving beats
/// from `Time::elapsed` instead would drift audibly inside a minute.
#[derive(Resource, Default)]
pub struct ScoreFeed {
    pub notes: Vec<RollNote>,
    pub pos: u64,
    pub bpm: f32,
    /// Quarter notes per bar — 4 in common time, 3 in a waltz or in 6/8.
    /// The roll draws a heavy line every this many beats.
    pub quarters_per_bar: u32,
    pub tonic: i32,
    /// Pitch classes that belong to the current mode — the piano roll
    /// bands its rows by this, so the backdrop visibly changes key.
    pub scale: [bool; 12],
}

#[derive(Clone, Copy)]
pub struct RollNote {
    pub at: u64,
    pub end: u64,
    pub midi: u8,
    pub voice: u8,
    pub vel: u8,
}

impl ScoreFeed {
    /// Seconds from the playhead to `at`; negative means already played.
    pub fn secs_from_now(&self, at: u64) -> f32 {
        (at as f64 - self.pos as f64) as f32 / SAMPLE_RATE as f32
    }
}

pub struct MusicPlugin;

impl Plugin for MusicPlugin {
    fn build(&self, app: &mut App) {
        let (tx, rx) = channel();
        let shared = Arc::new(Shared::default());
        let seed = seed_from_clock();
        // Built here rather than in a Startup system: bevy_state runs the
        // initial state's OnEnter before PreStartup, and that hook already
        // wants to pick a profile.
        app.insert_resource(MusicEngine {
            composer: Composer::new(seed),
            tx,
            shared: shared.clone(),
            scratch: Vec::with_capacity(512),
            profile: Profile::Ambient,
            profile_age: 0.0,
            intensity: 0.0,
            transpose: 0,
            announce: false,
        });
        app.insert_resource(PendingStream(Some(ChiptuneStream {
            rx: Mutex::new(Some(rx)),
            shared,
        })));
        app.init_resource::<ScoreFeed>()
            .add_audio_source::<ChiptuneStream>()
            .add_systems(Startup, start_stream)
            .add_systems(Update, (choose_profile, plan_music, announce_track).chain());
    }
}

/// Holds the asset until [`start_stream`] can reach `Assets<T>`.
#[derive(Resource)]
struct PendingStream(Option<ChiptuneStream>);

fn seed_from_clock() -> u64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0x5EED)
}

fn start_stream(
    mut commands: Commands,
    mut pending: ResMut<PendingStream>,
    mut assets: ResMut<Assets<ChiptuneStream>>,
    settings: Res<GameSettings>,
) {
    let Some(stream) = pending.0.take() else {
        return;
    };
    let handle = assets.add(stream);
    commands.spawn((
        // Tuple form: `AudioPlayer::new` exists only for the built-in
        // AudioSource.
        AudioPlayer(handle),
        // The spawn volume has to be right: `apply_bgm_volume` only
        // touches the sink when the duck factor moves or the settings
        // change, so a placeholder here would simply stay.
        PlaybackSettings::ONCE.with_volume(Volume::Linear(settings.bgm_linear())),
        // The existing volume/duck/pause systems key off this marker, so
        // they keep working untouched.
        Bgm,
    ));
}

/// Pick the musical personality from where the player actually is.
fn choose_profile(
    time: Res<Time>,
    app_state: Res<State<AppState>>,
    play_state: Option<Res<State<PlayState>>>,
    mode: Res<GameMode>,
    mut engine: ResMut<MusicEngine>,
) {
    let profile = match app_state.get() {
        AppState::Playing | AppState::Restarting => {
            if matches!(play_state.map(|s| *s.get()), Some(PlayState::Finished)) {
                Profile::Victory
            } else if matches!(*mode, GameMode::Single | GameMode::Sprint | GameMode::Dig) {
                Profile::SoloCalm
            } else {
                Profile::VsIntense
            }
        }
        _ => Profile::Ambient,
    };
    if profile != engine.profile {
        engine.profile = profile;
        engine.profile_age = 0.0;
        engine.transpose = 0;
        let i = engine.intensity;
        engine.composer.set_profile(profile, i);
        // Only the real music is worth naming; menus change too often.
        engine.announce = matches!(profile, Profile::SoloCalm | Profile::VsIntense);
    } else {
        engine.profile_age += time.delta_secs();
    }
}

/// Blend the gameplay signals into one 0..1 intensity and keep the score
/// filled ahead of the playhead.
fn plan_music(
    time: Res<Time>,
    danger: Option<Res<DangerLevel>>,
    sessions: Query<&GameSession, With<HumanControlled>>,
    mut engine: ResMut<MusicEngine>,
    mut feed: ResMut<ScoreFeed>,
) {
    let mut raw = danger.map(|d| d.0[0]).unwrap_or(0.0) * 0.62;
    let mut zone = false;
    for s in &sessions {
        // Garbage on the way and a combo running both raise the stakes
        // without the stack being tall yet.
        raw += 0.24 * (s.game.incoming_total() as f32 / 8.0).min(1.0);
        raw += 0.14 * (s.game.combo().max(0) as f32 / 6.0).min(1.0);
        zone |= s.game.zone_active();
    }
    let raw = raw.clamp(0.0, 1.0);
    // Asymmetric follower, same shape as the danger vignette's: rises
    // quickly, falls back slowly enough that one lucky clear does not
    // drop the music out of gear.
    let rate = if raw > engine.intensity { 3.0 } else { 1.2 };
    let dt = time.delta_secs();
    engine.intensity += (raw - engine.intensity) * (rate * dt).min(1.0);

    engine
        .shared
        .muffle
        .store(zone, std::sync::atomic::Ordering::Relaxed);

    let ctx = Context {
        profile: engine.profile,
        intensity: engine.intensity,
        transpose: engine.transpose,
        zone,
        elapsed: engine.profile_age,
    };
    let pos = engine.shared.pos();
    let lookahead = (LOOKAHEAD_SECS * SAMPLE_RATE as f32) as u64;

    let MusicEngine {
        composer,
        scratch,
        tx,
        ..
    } = &mut *engine;
    scratch.clear();
    composer.advance(pos, lookahead, &ctx, scratch);

    // Mirror every planned note to both consumers: the audio thread, and
    // the piano roll. Same notes, same timestamps, one clock.
    let info = composer.info();
    feed.pos = pos;
    feed.bpm = info.bpm;
    feed.quarters_per_bar = info.meter.quarters_per_bar();
    feed.tonic = info.tonic;
    feed.scale = [false; 12];
    for d in 0..7 {
        let pc = (info.tonic + info.mode.pitch(d)).rem_euclid(12) as usize;
        feed.scale[pc] = true;
    }
    for ev in scratch.iter() {
        // A closed channel only happens while the app is shutting down.
        let _ = tx.send(*ev);
        feed.notes.push(RollNote {
            at: ev.at,
            end: ev.at + ev.frames as u64 * SAMPLES_PER_FRAME as u64,
            midi: ev.midi,
            voice: ev.voice() as u8,
            vel: ev.vel,
        });
    }
    // Keep a few seconds of history for the trailing half of the roll.
    let cutoff = pos.saturating_sub(SAMPLE_RATE as u64 * 4);
    feed.notes.retain(|n| n.end >= cutoff);
}

/// Name the generated track in the corner, exactly where the old
/// "now playing" toast used to name the CC0 file.
fn announce_track(mut commands: Commands, mut engine: ResMut<MusicEngine>) {
    if !engine.announce {
        return;
    }
    engine.announce = false;
    let label = engine.composer.info().label();
    spawn_bgm_toast(&mut commands, &label);
}

#[cfg(test)]
mod tests {
    use super::*;
    use bevytris_chiptune::Inst;

    fn stream() -> (ChiptuneStream, Sender<NoteEvent>) {
        let (tx, rx) = channel();
        (
            ChiptuneStream {
                rx: Mutex::new(Some(rx)),
                shared: Arc::new(Shared::default()),
            },
            tx,
        )
    }

    #[test]
    fn the_decoder_runs_the_clock_and_plays_what_it_is_sent() {
        let (s, tx) = stream();
        let shared = s.shared.clone();
        let mut d = s.decoder();

        let quiet: f32 = (0..2_000).map(|_| d.next().unwrap().abs()).sum();
        assert!(quiet < 0.05, "an idle stream should be silent, got {quiet}");

        tx.send(NoteEvent {
            at: 2_500,
            inst: Inst::Pluck,
            midi: 69,
            vel: 120,
            frames: 40,
            arp: None,
        })
        .unwrap();
        let loud: f32 = (0..12_000).map(|_| d.next().unwrap().abs()).sum();
        assert!(loud > 1.0, "the scheduled note never sounded, got {loud}");

        // The clock only advances inside next(), which is what makes it
        // the one authority the piano roll can trust.
        assert!(shared.pos() >= 13_000, "clock stalled at {}", shared.pos());
    }

    #[test]
    fn the_stream_never_ends_even_when_the_composer_goes_away() {
        let (s, tx) = stream();
        assert_eq!(s.decoder().channels().get(), 1);
        assert_eq!(s.decoder().sample_rate().get(), SAMPLE_RATE);
        // total_duration() must stay None: a finite answer would let
        // PlaybackSettings::LOOP wrap us in rodio's buffering repeat.
        assert!(s.decoder().total_duration().is_none());

        let (s2, tx2) = stream();
        let mut d = s2.decoder();
        drop(tx2);
        drop(tx);
        for _ in 0..5_000 {
            assert!(d.next().is_some(), "stream ended after disconnect");
        }
    }

    #[test]
    fn the_decoder_is_only_handed_out_once() {
        let (s, _tx) = stream();
        let first = s.decoder();
        let mut second = s.decoder();
        assert!(first.rx.is_some());
        // A second decoder gets no channel rather than stealing events,
        // and still produces silence instead of panicking.
        assert!(second.rx.is_none());
        assert!(second.next().is_some());
    }
}
