//! Runtime BGM: the game has no music files. Every note you hear is
//! generated by `crates/chiptune` while you play.
//!
//! This file is only a bridge. The engine is one object with one job —
//! [`Director`]: hand it the gameplay parameters, ask it for samples.
//! The audio thread owns it and calls `next_frame`; the offline renderer
//! owns one and calls `fill`; they are running identical code.
//!
//! An earlier version split the composer onto the main thread and shipped
//! notes to the synthesizer over a channel, several seconds ahead of the
//! playhead. That meant every change of music had to hunt down a backlog
//! already in flight, and when that went wrong a screen transition kept
//! playing the old tune for the whole lookahead. Keeping the composer
//! next to the synthesizer deleted the lookahead, the generation stamps,
//! the stale-note drop and the re-anchor along with it. What crosses the
//! thread boundary now is a [`Context`] one way and a snapshot the other,
//! both behind a `try_lock` the audio thread is free to skip.
//!
//! Bevy's [`Decodable`] trait is what lets us hand raw PCM to `bevy_audio`
//! with no extra dependencies. Note that the stream is spawned with
//! [`PlaybackSettings::ONCE`], never `LOOP`: `LOOP` wraps the decoder in
//! rodio's `repeat_infinite`, which buffers every sample ever produced —
//! against a generator that never ends, that is an unbounded leak.
//! Repetition is the composer's job, not the mixer's.

use std::sync::Arc;
use std::sync::Mutex;
use std::sync::atomic::{AtomicU32, AtomicU64, Ordering};

use bevy::asset::Asset;
use bevy::audio::{AddAudioSource, ChannelCount, Decodable, SampleRate, Source, Volume};
use bevy::prelude::*;
use bevy::reflect::TypePath;

use bevytris_chiptune::Inst;
use bevytris_chiptune::compose::{Context, Groove, Info, Kit, Meter, Profile};
use bevytris_chiptune::director::Director;
use bevytris_chiptune::{NoteEvent, SAMPLE_RATE, SAMPLES_PER_FRAME};

use crate::audio::{Bgm, spawn_bgm_toast};
use crate::config::GameSettings;
use crate::effects::DangerLevel;
use crate::session::{GameSession, PrimaryPlayer, ZenPeak};
use crate::state::{AppState, GameMode, PlayState};

/// Everything the two threads say to each other.
///
/// Both mutexes are taken by the audio thread with `try_lock` once per
/// 60 Hz frame and skipped on contention, so it never blocks; the main
/// thread's own locks are uncontended microseconds.
/// Everything the main thread asks the engine for.
#[derive(Clone, Copy)]
pub struct Wanted {
    pub ctx: Context,
    pub seed: u64,
    /// Pinned time signature and drum kit; `None` lets each piece roll
    /// its own. Only the listening room sets these.
    pub meter: Option<Meter>,
    pub kit: Option<Kit>,
    /// What the piece is built around rhythmically; `None` lets each
    /// piece roll its own.
    pub groove: Option<Groove>,
    /// How stepwise the melodies are, 0..=1; `None` uses the profile's
    /// own default.
    pub smooth: Option<f32>,
    /// Melody instrument override; `None` lets each piece roll its own.
    pub lead: Option<Inst>,
}

pub struct Link {
    /// Main thread writes, audio thread reads.
    want: Mutex<Wanted>,
    /// Audio thread writes, main thread reads.
    out: Mutex<Snapshot>,
    /// The musical clock, in stereo frames.
    pos: AtomicU64,
    /// Instantaneous output level, for the visualizer.
    energy: AtomicU32,
}

#[derive(Default)]
struct Snapshot {
    info: Option<Info>,
    /// Notes composed since the main thread last collected them.
    notes: Vec<NoteEvent>,
    /// The final chorus changed key.
    modulated: bool,
    /// A new piece cut the old one off; drop any copy of the score.
    cut: bool,
}

impl Link {
    fn new(want: Wanted) -> Self {
        Link {
            want: Mutex::new(want),
            out: Mutex::new(Snapshot::default()),
            pos: AtomicU64::new(0),
            energy: AtomicU32::new(0),
        }
    }

    pub fn pos(&self) -> u64 {
        self.pos.load(Ordering::Relaxed)
    }

    pub fn energy(&self) -> f32 {
        f32::from_bits(self.energy.load(Ordering::Relaxed))
    }
}

// ---------------------------------------------------------------------------
// The streaming audio source
// ---------------------------------------------------------------------------

/// The asset `bevy_audio` plays. It carries no samples — the decoder it
/// hands out generates them.
#[derive(Asset, TypePath)]
pub struct ChiptuneStream {
    /// `decoder()` takes `&self` and is called exactly once, so the
    /// engine is handed over through an `Option` that gets emptied.
    director: Mutex<Option<Director>>,
    link: Arc<Link>,
}

pub struct ChiptuneDecoder {
    director: Option<Director>,
    link: Arc<Link>,
    frame_acc: u32,
    /// The right half of the frame we already generated. rodio wants
    /// interleaved samples, so each frame is handed over in two calls.
    pending_right: Option<f32>,
}

impl Iterator for ChiptuneDecoder {
    type Item = f32;

    fn next(&mut self) -> Option<f32> {
        if let Some(r) = self.pending_right.take() {
            return Some(r);
        }
        let Some(director) = &mut self.director else {
            return Some(0.0);
        };

        self.frame_acc += 1;
        if self.frame_acc >= SAMPLES_PER_FRAME {
            self.frame_acc = 0;
            // Both of these are try_lock: missing a frame costs 16 ms of
            // staleness and is far better than blocking the callback.
            if let Ok(want) = self.link.want.try_lock() {
                director.reseed(want.seed);
                director.pin_meter(want.meter);
                director.pin_kit(want.kit);
                director.pin_smoothness(want.smooth);
                director.pin_lead(want.lead);
                director.set_context(want.ctx);
            }
            if let Ok(mut out) = self.link.out.try_lock() {
                out.info = Some(director.info());
                out.modulated |= director.take_modulated();
                if director.take_cut() {
                    out.cut = true;
                    out.notes.clear();
                }
                director.drain_new_notes(&mut out.notes);
            }
            self.link
                .energy
                .store(director.envelope().to_bits(), Ordering::Relaxed);
        }
        self.link.pos.store(director.pos(), Ordering::Relaxed);
        let (l, r) = director.next_frame();
        self.pending_right = Some(r);
        Some(l)
    }
}

impl Source for ChiptuneDecoder {
    fn current_span_len(&self) -> Option<usize> {
        None
    }
    fn channels(&self) -> ChannelCount {
        ChannelCount::new(2).expect("stereo")
    }
    fn sample_rate(&self) -> SampleRate {
        SampleRate::new(SAMPLE_RATE).expect("nonzero sample rate")
    }
    fn total_duration(&self) -> Option<std::time::Duration> {
        // Never ends. This is what makes PlaybackSettings::LOOP the wrong
        // choice — see the module docs.
        None
    }
}

impl Decodable for ChiptuneStream {
    type Decoder = ChiptuneDecoder;

    fn decoder(&self) -> Self::Decoder {
        let director = self.director.lock().ok().and_then(|mut slot| slot.take());
        ChiptuneDecoder {
            director,
            link: self.link.clone(),
            frame_acc: 0,
            pending_right: None,
        }
    }
}

// ---------------------------------------------------------------------------
// Game side
// ---------------------------------------------------------------------------

/// The main-thread half: the gameplay signals, and whatever the engine
/// last reported back.
#[derive(Resource)]
pub struct MusicEngine {
    pub link: Arc<Link>,
    pub seed: u64,
    profile: Profile,
    profile_age: f32,
    intensity: f32,
    transpose: i32,
    info: Option<Info>,
    /// Notes seen so far — only the debug readout reads it.
    seen: u64,
    /// Set when the label should be re-announced in the corner.
    announce: bool,
}

impl MusicEngine {
    /// What the engine reports it is actually playing, once it has caught
    /// up with the last thing it was asked for. `None` for the frame or
    /// two after a switch, which is exactly when naming it would be wrong.
    pub fn now_playing(&self) -> Option<Info> {
        self.info.filter(|i| i.profile == self.profile)
    }
}

/// A window of the score around the playhead, for the piano-roll scene.
/// The scene and the sequencer therefore share one clock; deriving beats
/// from `Time::elapsed` instead would drift audibly inside a minute.
#[derive(Resource, Default)]
pub struct ScoreFeed {
    pub notes: Vec<RollNote>,
    pub pos: u64,
    pub bpm: f32,
    /// Quarter notes per bar — 4 in common time, 3 in a waltz or in 6/8.
    pub quarters_per_bar: u32,
    pub tonic: i32,
    /// Pitch classes that belong to the current mode — the piano roll
    /// bands its rows by this, so the backdrop visibly changes key.
    pub scale: [bool; 12],
}

#[derive(Clone, Copy)]
pub struct RollNote {
    pub at: u64,
    pub end: u64,
    pub midi: u8,
    pub voice: u8,
    pub vel: u8,
}

impl ScoreFeed {
    /// Seconds from the playhead to `at`; negative means already played.
    pub fn secs_from_now(&self, at: u64) -> f32 {
        (at as f64 - self.pos as f64) as f32 / SAMPLE_RATE as f32
    }
}

/// The listening room's settings. Only consulted while
/// [`AppState::Jukebox`] is active, so the rest of the game is unaffected
/// by whatever was left tuned in here.
#[derive(Resource, Clone, Copy)]
pub struct Jukebox {
    pub seed: u64,
    pub profile: Profile,
    /// `None` means "whatever this piece rolled".
    pub meter: Option<Meter>,
    pub kit: Option<Kit>,
    /// The rhythmic style; `None` = whatever this piece rolled.
    pub groove: Option<Groove>,
    /// How stepwise the melodies are, 0..=1; `None` = the profile default.
    pub smooth: Option<f32>,
    /// Melody instrument; `None` = whatever the piece rolled.
    pub lead: Option<Inst>,
    /// Stands in for the danger level, which there is no board to supply.
    pub intensity: f32,
    pub zone: bool,
}

impl Jukebox {
    pub fn new(seed: u64) -> Self {
        Jukebox {
            seed,
            profile: Profile::VsIntense,
            meter: None,
            kit: None,
            groove: None,
            smooth: None,
            lead: None,
            intensity: 0.45,
            zone: false,
        }
    }
}

/// `BEVYTRIS_MUSIC_DEBUG=1` puts a live readout of the music engine on
/// screen and logs every piece change.
///
/// This exists because the engine is otherwise hard to see into: the
/// score is composed a beat or two before you hear it, the audio thread
/// owns the clock, and "the music did not change" could equally mean the
/// profile never switched, or that it switched into an arrangement whose
/// opening bars are almost empty. Those need telling apart by looking.
#[derive(Resource, Clone, Copy)]
pub struct MusicDebug(pub bool);

#[derive(Component)]
struct MusicDebugText;

pub struct MusicPlugin;

impl Plugin for MusicPlugin {
    fn build(&self, app: &mut App) {
        let seed = music_seed();
        let ctx = Context::default();
        let link = Arc::new(Link::new(Wanted {
            ctx,
            seed,
            meter: None,
            kit: None,
            groove: None,
            smooth: None,
            lead: None,
        }));
        app.insert_resource(Jukebox::new(seed));
        // Built here rather than in a Startup system: bevy_state runs the
        // initial state's OnEnter before PreStartup, and that hook already
        // wants to pick a profile.
        app.insert_resource(MusicEngine {
            link: link.clone(),
            seed,
            profile: ctx.profile,
            profile_age: 0.0,
            intensity: 0.0,
            transpose: 0,
            info: None,
            seen: 0,
            announce: false,
        });
        app.insert_resource(PendingStream(Some(ChiptuneStream {
            director: Mutex::new(Some(Director::new(seed))),
            link,
        })));
        let debug = matches!(
            std::env::var("BEVYTRIS_MUSIC_DEBUG").as_deref(),
            Ok("1") | Ok("true")
        );
        app.insert_resource(MusicDebug(debug));
        app.init_resource::<ScoreFeed>()
            .add_audio_source::<ChiptuneStream>()
            .add_systems(Startup, start_stream)
            .add_systems(
                Update,
                (choose_profile, drive_music, announce_track, music_debug).chain(),
            );
    }
}

/// Holds the asset until [`start_stream`] can reach `Assets<T>`.
#[derive(Resource)]
struct PendingStream(Option<ChiptuneStream>);

/// `BEVYTRIS_MUSIC_SEED=<n>` pins the music so a session can be replayed
/// note for note; otherwise it comes from the clock. The seed is logged
/// either way, and its low bits show up in the corner toast, so a run
/// worth reproducing can be.
fn music_seed() -> u64 {
    if let Ok(raw) = std::env::var("BEVYTRIS_MUSIC_SEED") {
        if let Some(seed) = bevytris_chiptune::parse_seed(&raw) {
            info!("music: seed pinned to {seed} (0x{seed:x})");
            return seed;
        }
        warn!("music: BEVYTRIS_MUSIC_SEED={raw} is not a number, ignoring");
    }
    use std::time::{SystemTime, UNIX_EPOCH};
    let seed = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0x5EED);
    info!("music: seed {seed} (0x{seed:x}) — set BEVYTRIS_MUSIC_SEED to replay this session");
    seed
}

fn start_stream(
    mut commands: Commands,
    mut pending: ResMut<PendingStream>,
    mut assets: ResMut<Assets<ChiptuneStream>>,
    settings: Res<GameSettings>,
) {
    let Some(stream) = pending.0.take() else {
        return;
    };
    let handle = assets.add(stream);
    commands.spawn((
        // Tuple form: `AudioPlayer::new` exists only for the built-in
        // AudioSource.
        AudioPlayer(handle),
        // The spawn volume has to be right: `apply_bgm_volume` only
        // touches the sink when the duck factor moves or the settings
        // change, so a placeholder here would simply stay.
        PlaybackSettings::ONCE.with_volume(Volume::Linear(settings.bgm_linear())),
        // The existing volume/duck/pause systems key off this marker, so
        // they keep working untouched.
        Bgm,
    ));
}

/// Which musical personality belongs to a given place in the game.
/// `PlayState` only exists inside `Playing`, hence the `Option`.
fn profile_for(
    app: AppState,
    play: Option<PlayState>,
    mode: GameMode,
    jukebox: Profile,
    zen_peak: bool,
) -> Profile {
    match app {
        // The listening room picks its own.
        AppState::Jukebox => jukebox,
        AppState::Playing | AppState::Restarting => {
            if play == Some(PlayState::Finished) {
                Profile::Victory
            } else if mode == GameMode::Zen {
                // A zen run that reached terminal gravity has earned a
                // different piece to spend the rest of itself in.
                if zen_peak {
                    Profile::ZenPeak
                } else {
                    Profile::Zen
                }
            } else if matches!(mode, GameMode::Single | GameMode::Sprint) {
                Profile::SoloCalm
            } else {
                Profile::VsIntense
            }
        }
        _ => Profile::Ambient,
    }
}

/// Pick the musical personality from where the player actually is.
fn choose_profile(
    time: Res<Time>,
    app_state: Res<State<AppState>>,
    play_state: Option<Res<State<PlayState>>>,
    mode: Res<GameMode>,
    jukebox: Res<Jukebox>,
    zen_peak: Res<ZenPeak>,
    mut engine: ResMut<MusicEngine>,
) {
    let profile = profile_for(
        *app_state.get(),
        play_state.map(|s| *s.get()),
        *mode,
        jukebox.profile,
        zen_peak.0,
    );
    if profile != engine.profile {
        let was = engine.profile;
        engine.profile = profile;
        engine.profile_age = 0.0;
        engine.transpose = 0;
        // Only the real music is worth naming; menus change too often.
        // Zen's peak especially: the toast is what tells the player the
        // music just changed on purpose.
        engine.announce = matches!(
            profile,
            Profile::SoloCalm | Profile::VsIntense | Profile::ZenPeak
        );
        info!(
            "music: {was:?} -> {profile:?} | {:?} / {:?}",
            app_state.get(),
            mode.into_inner(),
        );
    } else {
        engine.profile_age += time.delta_secs();
    }
}

/// Blend the gameplay signals into one 0..1 intensity, hand the engine
/// the context, and collect whatever it composed since last frame.
fn drive_music(
    time: Res<Time>,
    app_state: Res<State<AppState>>,
    jukebox: Res<Jukebox>,
    danger: Option<Res<DangerLevel>>,
    sessions: Query<&GameSession, With<PrimaryPlayer>>,
    mut engine: ResMut<MusicEngine>,
    mut feed: ResMut<ScoreFeed>,
) {
    let listening = *app_state.get() == AppState::Jukebox;
    let mut raw = danger.map(|d| d.0[0]).unwrap_or(0.0) * 0.62;
    let mut zone = false;
    for s in &sessions {
        // Garbage on the way and a combo running both raise the stakes
        // without the stack being tall yet.
        raw += 0.24 * (s.game.incoming_total() as f32 / 8.0).min(1.0);
        raw += 0.14 * (s.game.combo().max(0) as f32 / 6.0).min(1.0);
        zone |= s.game.zone_active();
    }
    if listening {
        // No board to read, so the listener supplies the dial directly.
        raw = jukebox.intensity;
        zone = jukebox.zone;
    }
    let raw = raw.clamp(0.0, 1.0);
    // Asymmetric follower, same shape as the danger vignette's: rises
    // quickly, falls back slowly enough that one lucky clear does not
    // drop the music out of gear.
    let rate = if raw > engine.intensity { 3.0 } else { 1.2 };
    engine.intensity += (raw - engine.intensity) * (rate * time.delta_secs()).min(1.0);

    // Parameters in.
    if let Ok(mut want) = engine.link.clone().want.lock() {
        want.ctx = Context {
            profile: engine.profile,
            intensity: engine.intensity,
            transpose: engine.transpose,
            zone,
            elapsed: engine.profile_age,
        };
        if listening {
            want.seed = jukebox.seed;
            want.meter = jukebox.meter;
            want.kit = jukebox.kit;
            want.groove = jukebox.groove;
            want.smooth = jukebox.smooth;
            want.lead = jukebox.lead;
        } else {
            want.seed = engine.seed;
            want.meter = None;
            want.kit = None;
            want.smooth = None;
            want.lead = None;
        }
    }

    // Score out.
    let link = engine.link.clone();
    let pos = link.pos();
    let mut fresh: Vec<NoteEvent> = Vec::new();
    let mut modulated = false;
    let mut cut = false;
    let mut info_now = None;
    if let Ok(mut out) = link.out.lock() {
        info_now = out.info;
        modulated = std::mem::take(&mut out.modulated);
        cut = std::mem::take(&mut out.cut);
        std::mem::swap(&mut fresh, &mut out.notes);
    }
    if cut {
        // The piano roll must not keep drawing a piece that has stopped.
        feed.notes.clear();
    }
    if info_now.is_some() {
        engine.info = info_now;
    }
    engine.seen += fresh.len() as u64;
    if modulated {
        // The final chorus lifted the key: say so, since the toast names it.
        engine.announce = true;
    }

    let Some(info) = engine.info else {
        return;
    };
    feed.pos = pos;
    feed.bpm = info.bpm;
    feed.quarters_per_bar = info.meter.quarters_per_bar();
    feed.tonic = info.tonic;
    feed.scale = [false; 12];
    for d in 0..7 {
        let pc = (info.tonic + info.mode.pitch(d)).rem_euclid(12) as usize;
        feed.scale[pc] = true;
    }
    for ev in &fresh {
        feed.notes.push(RollNote {
            at: ev.at,
            end: ev.at + ev.frames as u64 * SAMPLES_PER_FRAME as u64,
            midi: ev.midi,
            voice: ev.voice() as u8,
            vel: ev.vel,
        });
    }
    // Keep a few seconds of history for the trailing half of the roll.
    let cutoff = pos.saturating_sub(SAMPLE_RATE as u64 * 4);
    feed.notes.retain(|n| n.end >= cutoff);
}

/// Name the generated track in the corner, exactly where the old
/// "now playing" toast used to name the CC0 file.
fn announce_track(mut commands: Commands, mut engine: ResMut<MusicEngine>) {
    if !engine.announce {
        return;
    }
    // Nothing to name until the engine has reported a piece — and not
    // until it has reported the *new* one. The snapshot lags the context
    // by up to a 60 Hz tick, so naming whatever is in it right after a
    // switch names the piece that just ended.
    let Some(info) = engine.now_playing() else {
        return;
    };
    engine.announce = false;
    spawn_bgm_toast(&mut commands, &info.label());
}

/// Live readout of everything the ear cannot check for itself.
fn music_debug(
    mut commands: Commands,
    debug: Res<MusicDebug>,
    engine: Res<MusicEngine>,
    feed: Res<ScoreFeed>,
    mut text: Query<&mut Text, With<MusicDebugText>>,
) {
    if !debug.0 {
        return;
    }
    let Some(info) = engine.info else {
        return;
    };
    let body = format!(
        "{:?} bar {} | {} | {} kit | seed 0x{:x}\n\
         layers: {}\n\
         playhead {:.1}s  intensity {:.2}  age {:.1}s\n\
         notes {}  live {}  energy {:.2}",
        engine.profile,
        info.bar,
        info.label(),
        info.kit.name(),
        engine.seed,
        // The line that would have made the bare-opening bug obvious in a
        // glance instead of by counting notes.
        info.layer_list(),
        engine.link.pos() as f32 / SAMPLE_RATE as f32,
        engine.intensity,
        engine.profile_age,
        engine.seen,
        feed.notes.len(),
        engine.link.energy(),
    );
    if let Ok(mut t) = text.single_mut() {
        t.0 = body;
        return;
    }
    commands.spawn((
        Node {
            position_type: PositionType::Absolute,
            left: Val::Px(10.0),
            top: Val::Px(10.0),
            ..default()
        },
        Text::new(body),
        TextFont {
            font_size: FontSize::Px(15.0),
            ..default()
        },
        TextColor(Color::srgba(0.7, 1.0, 0.8, 0.9)),
        GlobalZIndex(40),
        Pickable::IGNORE,
        MusicDebugText,
    ));
}

#[cfg(test)]
mod tests {
    use super::*;

    fn stream() -> ChiptuneStream {
        ChiptuneStream {
            director: Mutex::new(Some(Director::new(1234))),
            link: Arc::new(Link::new(Wanted {
                ctx: Context::default(),
                seed: 1234,
                meter: None,
                kit: None,
                groove: None,
                smooth: None,
                lead: None,
            })),
        }
    }

    fn energy(d: &mut ChiptuneDecoder, n: usize) -> f32 {
        (0..n).map(|_| d.next().unwrap().abs()).sum()
    }

    #[test]
    fn every_screen_maps_to_the_right_music() {
        use AppState::*;
        // Menus are menus whatever mode is selected behind them.
        for mode in [
            GameMode::Single,
            GameMode::Sprint,
            GameMode::Zen,
            GameMode::VsCpu { stage: 15 },
            GameMode::ZoneBattle { stage: 15 },
            GameMode::Custom,
        ] {
            for app in [
                Title,
                Settings,
                SoloSelect,
                StageSelect,
                ZoneSelect,
                CustomSetup,
                // The character picker sits between a menu and a match; it
                // keeps the menu's music, so the tune the match rolls
                // starts with the match.
                CharacterSelect,
            ] {
                assert_eq!(
                    profile_for(app, None, mode, Profile::VsIntense, false),
                    Profile::Ambient,
                    "{app:?} should stay on menu music"
                );
            }
            // The listening room answers to its own dial, not the mode
            // sitting behind it.
            for want in Profile::ALL {
                assert_eq!(profile_for(Jukebox, None, mode, want, false), want);
            }
            // A match is a match from the countdown onwards.
            for play in [
                PlayState::Countdown,
                PlayState::Running,
                PlayState::Paused,
                PlayState::RoundOver,
            ] {
                let want = match mode {
                    GameMode::Zen => Profile::Zen,
                    GameMode::Single | GameMode::Sprint => Profile::SoloCalm,
                    _ => Profile::VsIntense,
                };
                assert_eq!(
                    profile_for(Playing, Some(play), mode, Profile::Ambient, false),
                    want,
                    "{mode:?}"
                );
                // Only zen has a second half, and only zen may hear it:
                // every other mode ignores the flag entirely.
                let peaked = if mode == GameMode::Zen {
                    Profile::ZenPeak
                } else {
                    want
                };
                assert_eq!(
                    profile_for(Playing, Some(play), mode, Profile::Ambient, true),
                    peaked,
                    "{mode:?} at peak"
                );
            }
            // The result screen is a fanfare regardless of mode.
            assert_eq!(
                profile_for(
                    Playing,
                    Some(PlayState::Finished),
                    mode,
                    Profile::Ambient,
                    false
                ),
                Profile::Victory
            );
            // A restart bounces through Restarting with no PlayState at
            // all; the music must not fall back to the menu for that frame.
            assert_ne!(
                profile_for(Restarting, None, mode, Profile::Ambient, false),
                Profile::Ambient
            );
        }
    }

    #[test]
    fn the_decoder_makes_sound_and_runs_the_clock() {
        let s = stream();
        let link = s.link.clone();
        let mut d = s.decoder();
        {
            let mut w = link.want.lock().unwrap();
            w.ctx.profile = Profile::VsIntense;
            w.ctx.elapsed = 600.0;
        }
        let level = energy(&mut d, 96_000);
        assert!(level > 100.0, "a second of music produced {level}");
        // The clock counts stereo frames, so 96 000 calls is 48 000.
        assert!(link.pos() >= 47_000, "clock stalled at {}", link.pos());
        assert!(link.energy() > 0.0);
    }

    #[test]
    fn the_engine_reports_back_what_it_composed() {
        let s = stream();
        let link = s.link.clone();
        let mut d = s.decoder();
        {
            let mut w = link.want.lock().unwrap();
            w.ctx.profile = Profile::SoloCalm;
            w.ctx.elapsed = 600.0;
        }
        energy(&mut d, 96_000 * 3);
        let out = link.out.lock().unwrap();
        assert!(out.info.is_some(), "no snapshot published");
        assert!(!out.notes.is_empty(), "no notes published");
        assert!(out.notes.windows(2).all(|w| w[0].at <= w[1].at));
    }

    #[test]
    fn the_stream_never_ends() {
        let s = stream();
        assert_eq!(s.decoder().channels().get(), 2);
        assert_eq!(s.decoder().sample_rate().get(), SAMPLE_RATE);
        // total_duration() must stay None: a finite answer would let
        // PlaybackSettings::LOOP wrap us in rodio's buffering repeat.
        assert!(s.decoder().total_duration().is_none());
        // A second decoder gets no engine rather than stealing it, and
        // still produces silence instead of panicking.
        let mut second = s.decoder();
        for _ in 0..5_000 {
            assert_eq!(second.next(), Some(0.0));
        }
    }

    #[test]
    fn the_stream_is_interleaved_stereo() {
        let s = stream();
        let link = s.link.clone();
        let mut d = s.decoder();
        {
            let mut w = link.want.lock().unwrap();
            w.ctx.profile = Profile::VsIntense;
            w.ctx.elapsed = 600.0;
        }
        let mut left = 0.0f32;
        let mut right = 0.0f32;
        for i in 0..192_000 {
            let v = d.next().unwrap().abs();
            if i % 2 == 0 { left += v } else { right += v }
        }
        assert!(left > 0.0 && right > 0.0);
        // The image is spread but roughly balanced; a mono decoder or a
        // broken interleave would make these identical.
        assert_ne!(left, right);
        assert!((left - right).abs() / (left + right) < 0.25, "lopsided mix");
    }

    /// The toast used to name the piece that had just *ended*: the
    /// snapshot lags the context by up to one 60 Hz tick, so reading it
    /// on the frame of the switch describes the outgoing music.
    #[test]
    fn a_snapshot_says_which_piece_it_describes() {
        let s = stream();
        let link = s.link.clone();
        let mut d = s.decoder();
        link.want.lock().unwrap().ctx.profile = Profile::Ambient;
        energy(&mut d, 96_000);
        assert_eq!(
            link.out.lock().unwrap().info.unwrap().profile,
            Profile::Ambient
        );

        link.want.lock().unwrap().ctx.profile = Profile::VsIntense;
        // Not a single frame yet: the snapshot must still say Ambient, so
        // a caller can tell it has not caught up.
        assert_eq!(
            link.out.lock().unwrap().info.unwrap().profile,
            Profile::Ambient
        );
        energy(&mut d, 9_600);
        assert_eq!(
            link.out.lock().unwrap().info.unwrap().profile,
            Profile::VsIntense,
            "the snapshot never caught up with the new piece"
        );
    }

    /// The bug this architecture exists to make impossible.
    #[test]
    fn a_screen_change_changes_the_music_at_once() {
        let s = stream();
        let link = s.link.clone();
        let mut d = s.decoder();
        link.want.lock().unwrap().ctx.profile = Profile::Ambient;
        energy(&mut d, 96_000 * 3);
        let before = link.out.lock().unwrap().info.unwrap();

        link.want.lock().unwrap().ctx.profile = Profile::VsIntense;
        // Half a second is more than enough: the switch lands on the next
        // 60 Hz tick and the new piece starts from there.
        energy(&mut d, 48_000);
        let after = link.out.lock().unwrap().info.unwrap();
        assert_ne!(
            (before.bpm, before.tonic, before.meter),
            (after.bpm, after.tonic, after.meter),
            "the music did not change"
        );
    }

    #[test]
    fn a_pinned_seed_replays_the_same_music() {
        let render = || {
            let s = ChiptuneStream {
                director: Mutex::new(Some(Director::new(0x1234_5678))),
                link: Arc::new(Link::new(Wanted {
                    ctx: Context {
                        profile: Profile::VsIntense,
                        elapsed: 600.0,
                        ..Default::default()
                    },
                    seed: 0x1234_5678,
                    meter: None,
                    kit: None,
                    groove: None,
                    smooth: None,
                    lead: None,
                })),
            };
            let mut d = s.decoder();
            (0..96_000).map(|_| d.next().unwrap()).collect::<Vec<_>>()
        };
        assert_eq!(render(), render());
    }
}
